# Generated by Django 3.0.6 on 2020-07-11 10:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findApp', '0007_auto_20200506_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка скрапинга',
                'verbose_name_plural': 'Ошибки скрапинга',
                'ordering': ['-timestamp'],
            },
        ),
    ]
